[Hufi-apikey] feat : add apikey to hufi job launcher
humanprotocol/human-protocol pull request #1303
Opened 2023-12-04 12:10 UTC by mrhouzlane

## Description 

Follow the same iteration for adding api-key to JobLauncher and adapt to Campaigns. 

## Summary of changes

- Added endpoint to generate api-key.

2023-12-04 12:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/humanprotocol/human-protocol?pullRequest=1303) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/humanprotocol/human-protocol?pullRequest=1303) before we can accept your contribution.<br/><hr/>**Mehdi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/humanprotocol/human-protocol?pullRequest=1303) it.</sub>

2023-12-04 15:17 UTC, portuu3 requested changes

2023-12-04 15:17 UTC, portuu3 commented on packages/apps/hufi/job-launcher/server/src/common/constants/errors.ts
> +
```suggestion
  ApiKeyNotFound = 'API key not found',
```

2023-12-04 15:17 UTC, portuu3 commented on packages/apps/hufi/job-launcher/server/src/modules/job/job.controller.ts
> +import { JobRequestType, JobStatusFilter } from '../../common/enums/job';
```suggestion
import { JobStatusFilter } from '../../common/enums/job';
```

2023-12-11 12:45 UTC, mrhouzlane commented on packages/apps/hufi/job-launcher/server/src/modules/job/job.controller.ts
> +import { JobRequestType, JobStatusFilter } from '../../common/enums/job';
done

2023-12-11 12:45 UTC, mrhouzlane commented on packages/apps/hufi/job-launcher/server/src/modules/job/job.controller.ts
> +
I don't get this. removed the line .. 
Done ?

2024-01-08 12:06 UTC, portuu3 commented
Hufi is going to have its own repo

2024-01-08 12:06 UTC, closed without merging