feat : Core contracts with foundry
humanprotocol/human-protocol pull request #1465
Opened 2024-01-16 09:17 UTC by mrhouzlane

## Description

Integrate Core contracts and Governance contracts using Foundry instead of Hardhat.   

## Summary of changes

- Add script to upgrade proxies in Solidity.

2024-01-30 10:30 UTC, portuu3 requested changes

2024-01-30 10:30 UTC, portuu3 commented on package-lock.json
Remove this file

2024-01-30 10:30 UTC, portuu3 commented on packages/core/package.json
> +    "description": "Core Human Protocol contracts ",
```suggestion
    "description": "Human Protocol Core Smart Contracts",
```

2024-01-30 10:30 UTC, portuu3 commented on packages/core/package.json
> +    "name": "core-human-contracts",
```suggestion
    "name": "@human-protocol/core",
```

2024-01-30 10:30 UTC, portuu3 commented on packages/core/foundry.toml
> +[rpc_endpoints]
remove unnecessary networks

2024-01-30 10:30 UTC, portuu3 commented on packages/core/foundry.toml
> +scrollSepolia = { key = "${ETHERSCAN_API_KEY}" , url = "https://api-sepolia.scrollscan.dev/api" }
remove

2024-01-30 10:30 UTC, portuu3 commented on packages/core/test.md
Remove this file

2024-01-30 10:30 UTC, portuu3 commented on packages/core/sample-spoke-params.json
what is this?

2024-01-30 10:30 UTC, portuu3 commented on packages/core/src/hm-token/HMToken.sol
we have two versions of HM Token

2024-01-31 08:19 UTC, mrhouzlane commented on packages/core/sample-spoke-params.json
this is from governance

2024-01-31 08:32 UTC, mrhouzlane commented on packages/core/src/hm-token/HMToken.sol
removed duplicate

2024-01-31 08:32 UTC, mrhouzlane commented on packages/core/package.json
> +    "name": "core-human-contracts",
change done

2024-01-31 08:32 UTC, mrhouzlane commented on packages/core/package.json
> +    "description": "Core Human Protocol contracts ",
change done

2024-02-02 08:47 UTC, closed without merging