Avalanche Support for Human Protocol
humanprotocol/human-protocol pull request #158
Opened 2023-01-10 17:13 UTC by hrik2001

## Description

PR that aims to add support of Avalanche mainnet and testnet, as discussed in #137 

## Summary of changes

Added network details to `escrow-dashboard` and `CONTRACT_LIST.md`

2023-01-11 12:35 UTC, posix4e commented
Where is fortune running?

2023-01-11 21:16 UTC, hrik2001 commented
@posix4e I had deployed the fortune app locally, that ran on
- Fujinet (Avalanche testnet)
- Avalanche C-Chain

[Testnet Video Demo](https://www.loom.com/share/f32cc0e4ca8748ccbb654b81920591a8)
[Mainnet Video Demo](https://www.loom.com/share/50883365395c43bc9cdf7c83c1394a24)

2023-01-16 11:16 UTC, foufrix commented
@posix4e everything is on this message on this avalanche issue : https://github.com/humanprotocol/human-protocol/issues/137#issuecomment-1372085275

2023-01-16 11:17 UTC, foufrix approved these changes

2023-01-16 11:18 UTC, foufrix requested changes
The previous change that you published on the previous repo @hrik2001 (the config for deployment here : https://github.com/humanprotocol/hmt-escrow/pull/430/files#diff-5f1179b38d94a75785290064a194e2fd668a28ccbb30b8784d1cc34bafeb35f6) need to be added to `hardhat.config.ts` file in `core` https://github.com/humanprotocol/human-protocol/blob/main/packages/core/hardhat.config.ts

Apart from that looks good to me

2023-01-16 14:50 UTC, portuu3 commented
@hrik2001 please verify the contracts in both testnet and mainnet scanners

2023-01-16 14:57 UTC, portuu3 requested changes

2023-01-16 14:57 UTC, portuu3 commented on CONTRACTS_LIST.md
> +| Moonbeam | Mainnet | Active | 0x12365293cb6477d4fc2686e46BB97E3Fb64f1550 |  | 0x9767a578ba7a5FA1563c8229943cB01cd8446BB4 | | |
I think should be Avalanche instead of Moonbeam here

2023-01-17 17:54 UTC, portuu3 commented
Fortune works for both testnet and mainnet. Waiting for changes requested

2023-01-18 08:08 UTC, hrik2001 commented
Hi, thanks @foufrix @portuu3, had to run some errands hence couldn't do the changes. Changes will be done in an hour , thanks a lot :)

2023-01-19 08:09 UTC, portuu3 commented
@hrik2001 contracts still not verified

2023-01-19 08:28 UTC, foufrix submitted a review, later dismissed

2023-01-19 08:48 UTC, portuu3 commented
@foufrix I cannot be approved and merged yet, if we merge now we will break the dashboard since the subgraphs are not done.
@hrik2001 please can you implement subgraphs too?

2023-01-19 10:20 UTC, hrik2001 commented
@portuu3 sure, so essentially I have to add configs for avalanche at `human-protocol/packages/sdk/typescript/subgraph/config/` right?

Also you had said
> contracts still not verified

I am not sure what you mean by this, how should I go about that?

2023-01-19 11:24 UTC, portuu3 commented
> Also you had said
> 
> > contracts still not verified
> 
> I am not sure what you mean by this, how should I go about that?

If you click in the contract tab of the scanner you will have an option to verify it. Just click on it and go trough the process, it will ask you to upload the source code of the contracts you used.
![image](https://user-images.githubusercontent.com/61605646/213429895-923944a8-0785-4199-97bd-e5447bb661d9.png)

2023-01-19 11:34 UTC, portuu3 commented
> @portuu3 sure, so essentially I have to add configs for avalanche at `human-protocol/packages/sdk/typescript/subgraph/config/` right?

The section `Add a new network` in `human-protocol/packages/sdk/typescript/subgraph/README.md` should help you

2023-01-24 19:24 UTC, hrik2001 commented
@portuu3 just wanted to confirm, if I host the subgraph, there would be my username in the subgraph link and not human protocol, you guys are okay with that right?

2023-01-25 07:56 UTC, portuu3 commented
> @portuu3 just wanted to confirm, if I host the subgraph, there would be my username in the subgraph link and not human protocol, you guys are okay with that right?

@hrik2001 just do the changes in the repo and I can do the step for creating the subgraph

2023-01-30 22:29 UTC, hrik2001 commented
@portuu3 feel free to review

2023-01-31 10:31 UTC, portuu3 approved these changes

2023-01-31 10:35 UTC, merged