[Reputation Oracle] Completed webhook
humanprotocol/human-protocol pull request #1636
Opened 2024-02-27 12:28 UTC by flopez7

## Description

Send a webhook from Reputation Oracle to Job Launcher and Recording Oracle once the escrow is completed

*(Waiting #1620 to complete Job Launcher webhook handling)  

## Summary of changes

Add a new method inside webhook.service.ts to send a webhook
In cron-job.service.ts send gets the job launcher and recording oracle webhhook urls and send the webhook
Update all tests

## How test the changes

`yarn test`

## Related issues
#1625

2024-02-27 15:40 UTC, mrhouzlane commented
https://github.com/humanprotocol/human-protocol/blob/74ff5cb7ed01333580a3bd840d699438c189898d/packages/apps/reputation-oracle/server/src/common/enums/role.ts#L2

- Check `JobLauncher` typo

2024-03-04 11:14 UTC, portuu3 requested changes

2024-03-04 11:14 UTC, portuu3 commented on packages/apps/job-launcher/server/src/modules/job/job.service.ts
> +  public async escrowCompletedWebhook(dto: WebhookDataDto): Promise<void> {
rename to completeJob

2024-03-08 09:27 UTC, portuu3 approved these changes

2024-03-08 09:28 UTC, merged