[CVAT] Oracles M2 API - endpoints
humanprotocol/human-protocol pull request #1649
Opened 2024-02-29 11:02 UTC by zhiltsov-max

## Description

## Summary of changes

Depends on #1621 

- Upgraded pydantic to v2 and fastapi to 0.109, migrated code
- Updated ExcOr endpoints (GET /job, POST | GET /assignment, PUT /register)

TBD:
- [ ] Fix discrepancies between doc and SoW APIs
- [ ] Rename "items" to "results" in list endpoints
- [ ] Upgrade deps in RecOr

## How test the changes

## Related issues
[Keywords for linking issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

2024-08-08 10:07 UTC, Dzeranov requested changes

2024-08-08 10:07 UTC, Dzeranov commented on packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py
> +        stats["assignments_amount"] = (
`assignments_total`

2024-08-08 10:07 UTC, Dzeranov commented on packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py
> +        stats["workers_amount"] = session.query(cvat_service.User.wallet_address).count()
`workers_total`

2024-08-14 11:05 UTC, zhiltsov-max commented on packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py
> +        stats["workers_amount"] = session.query(cvat_service.User.wallet_address).count()
Fixed

2024-08-14 11:05 UTC, zhiltsov-max commented on packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py
> +        stats["assignments_amount"] = (
Fixed

2024-08-14 11:05 UTC, zhiltsov-max commented on packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py
> +    created_after: Optional[datetime] = Query(default=None),
Added

2024-08-14 11:05 UTC, zhiltsov-max commented on packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py
>              cvat_email=email_db_user.cvat_email,
Changed

2024-08-14 11:05 UTC, zhiltsov-max commented on packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py
> +@router.put("/register", description="Binds a CVAT user to a HUMAN App user")
Changed

2024-08-19 08:37 UTC, Dzeranov approved these changes

2024-08-19 08:38 UTC, merged