[Fortune] Add endpoint for workers stats
humanprotocol/human-protocol pull request #1717
Opened 2024-03-15 12:08 UTC by mrhouzlane

## Description

Implement an endpoint that follows the [standard](https://docs.humanprotocol.org/human-tech-docs/exchange-oracle#get-assignment-stats).

## Summary of changes

- Add `AssignmentController`
- Add `AssignmentService` 
- Add `AssignmentStatsDto`

2024-03-18 13:15 UTC, flopez7 requested changes

2024-03-18 13:15 UTC, flopez7 commented on packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.dto.ts
> +  assignments_expired: number;
We have an interceptor inside API to convert camelCase objects to snake_case so let's use camelCase inside the code. Also, I think this should be inside `stats.dto.ts`

2024-03-18 13:15 UTC, flopez7 commented on packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.spec.ts
Remove this file

2024-03-18 13:15 UTC, flopez7 commented on packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.controller.ts
This should be a new Stats controller

2024-03-18 13:15 UTC, flopez7 commented on packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.ts
> +    finalStats.assignments_expired = stats.assignments_expired;
Why don't you use the constructor?

2024-03-19 14:18 UTC, mrhouzlane commented on packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.spec.ts
Removed

2024-03-19 14:18 UTC, mrhouzlane commented on packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.controller.ts
Changed to `StatsController`

2024-03-19 14:19 UTC, mrhouzlane commented on packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.ts
> +    finalStats.assignments_expired = stats.assignments_expired;
Added a constructor

2024-03-19 14:25 UTC, flopez7 requested changes
As it's a new module, you have to create the new `stats.module.ts` and also import the `StatsModule` inside `app.module.ts`

2024-03-19 18:23 UTC, merged