[SDK] Enhance Operator Data
humanprotocol/human-protocol pull request #1849
Opened 2024-04-10 07:21 UTC by mrhouzlane

## Description

Enhance the response of getReputationNetworkOperators by including additional properties from the KV store: "url" and "job_types". This enhancement will facilitate more comprehensive oracle discovery with a single request

## Proposed implementation 

TypeScript  : 
Modify `getReputationNetworkOperators` to fetch and append `url` and `job_types` properties for each operator from the KV store.

2024-04-12 16:21 UTC, portuu3 requested changes
Apply the same comments to python.
You should also regenerate the python docs: `make generate-doc-md` in python sdk folder

2024-04-12 16:21 UTC, portuu3 commented on packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts
> +  url: string;
this should be nullable

2024-04-12 16:21 UTC, portuu3 commented on packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts
> +  jobTypes: string;
This should be nullable.
Lets make jobTypes a string[], use split function

2024-04-15 05:50 UTC, portuu3 requested changes

2024-04-15 05:50 UTC, portuu3 commented on packages/apps/job-launcher/server/test/setup.ts
> +    ],
Keep it simple
```suggestion
  await kvStoreClient.setBulk(
    [
      KVStoreKeys.role,
      KVStoreKeys.fee,
      KVStoreKeys.webhookUrl,
      KVStoreKeys.url,
      KVStoreKeys.jobTypes,
    ],
    [
      Role.JobLauncher,
      '1',
      'http://localhost:5000/webhook',
      'http://localhost:5000',
      'type1,type2',
    ],
```

2024-04-15 05:50 UTC, portuu3 commented on packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/operator/test_operator_utils.py
> +        job_types = ["type1, type2"]
```suggestion
        job_types = ["type1", "type2"]
```

2024-04-15 07:54 UTC, mrhouzlane commented on packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py
> -        "subgraph_url": "subgraph_url",
do we have to make this change ?

2024-04-15 08:31 UTC, portuu3 approved these changes

2024-04-15 08:32 UTC, merged