[Job Launcher] Implemented e2e create Fortune workflow
humanprotocol/human-protocol pull request #1851
Opened 2024-04-11 05:30 UTC by eugenvoronov

## Description
Implemented e2e create Fortune workflow.

## Summary of changes
- Added end-to-end tests using Supertest to simulate HTTP requests.
- Implemented tests for Fortune.
- Covered successful flow, not enough funds, manifest hash does not exist.

## How test the changes
`yarn test:e2e`

## Related issues
[Job Launcher] Implement e2e launching Fortune job workflow
[#1841](https://github.com/humanprotocol/human-protocol/issues/1841)

2024-04-17 09:37 UTC, portuu3 requested changes

2024-04-17 09:37 UTC, portuu3 commented on packages/apps/job-launcher/server/test/e2e/fortune-workflow.e2e-spec.ts
> +    const paymentEntities = await paymentRepository.findByUserAndStatus(
Would be good to check the balance and amounts in payments

2024-05-13 12:28 UTC, flopez7 approved these changes

2024-05-15 10:03 UTC, portuu3 approved these changes

2024-05-15 10:03 UTC, merged