[Fortune Exchange Oracle] RPC urls as environment variables
humanprotocol/human-protocol pull request #1917
Opened 2024-04-24 15:09 UTC by flopez7

## Description

Set the RPC urls as environment variables to improve security of our RPCs

## Summary of changes

Create a new `network-config.service.ts` to read .env variables 

## How test the changes

`yarn test`

## Related issues
#1888

2024-04-26 13:45 UTC, leric7 requested changes
- I think it's better to manage RPC urls on Vercel, env files, etc if we use`RPC_URL` as prefix rather than suffix for env variables. I already merged couple PRs using this prefix approach in the codebase, so it's good to use same pattern across the entire codebase, as well.
- In addition, please update `.env.example` file by adding these new env variables.

2024-05-07 14:13 UTC, leric7 approved these changes

2024-05-07 20:44 UTC, portuu3 commented on packages/apps/fortune/exchange-oracle/server/src/common/config/env-schema.ts
> +  RPC_URL_GOERLI: Joi.string(),
Remove Goerli, it is deprecated

2024-05-09 07:28 UTC, portuu3 approved these changes

2024-05-09 07:28 UTC, merged