[SDK] Added daily stats to ts sdk
humanprotocol/human-protocol pull request #2115
Opened 2024-06-07 06:35 UTC by eugenvoronov

## Description
Created an subgraph entity dailyStats with the properties specified in the implementation details.

## Summary of changes
- [ ] Implemented getDailyStats for Typescript SDK
- [ ] Implemented unit tests for Typescript SDK
- [ ] Implemented getDailyStats for Python SDK
- [ ] Implemented unit tests for Python SDK

## How test the changes
**Typescript**
```
const statisticsClient = new StatisticsClient(NETWORKS[ChainId.POLYGON_AMOY]);
const dailyStats = await statisticsClient.getDailyStats();

console.log('Daily statistics:', dailyStats);

const dailyStatsRange = await statisticsClient.getDailyStats();

console.log('Daily statistics from 5/8 - 6/8:', dailyStatsRange);
```

`yarn test`

## Related issues
[SDK] Daily statistics
[#2084](https://github.com/humanprotocol/human-protocol/issues/2084)

2024-06-13 09:09 UTC, eugenvoronov commented on packages/sdk/typescript/subgraph/src/mapping/Escrow.ts
> +  dailyStats.escrowPayouts = dailyStats.escrowPayouts.plus(ONE_BI);
Works as a payout counter.

2024-06-17 13:19 UTC, portuu3 requested changes

2024-06-17 13:19 UTC, portuu3 commented on packages/sdk/python/human-protocol-sdk/human_protocol_sdk/statistics/statistics_client.py
> +        self.total_transaction_amount = total_transaction_amount
it is duplicated

2024-06-17 13:19 UTC, portuu3 commented on packages/sdk/typescript/subgraph/src/mapping/utils/dayUpdates.ts
> +    eventDayData.uniqueSenders = ZERO_BI;
can you please rename to follow the same structure dailyUniqueSenders and dailyUniqueReceivers?

2024-06-17 13:19 UTC, portuu3 commented on packages/sdk/typescript/subgraph/schema.graphql
> +type UniqueSender @entity {
You don't need these new entities. You can check hmt transfer events of the day to know if the this wallet was already a sender or receiver.

2024-06-18 15:27 UTC, portuu3 approved these changes

2024-06-18 15:27 UTC, merged