[Reputation Oracle] Qualification module
humanprotocol/human-protocol pull request #2192
Opened 2024-06-26 04:41 UTC by eugenvoronov

## Description
Implemented a Qualification module to manage qualifications within protocol. 

## Summary of changes

- [x] Created Qualification entity - This enitity will store the data about Qualification (title, description and etc) with ManyToMany relation to User Entity.
- [x] Implemented QualificationService for business logic.
- [x] Implemented QualificationRepository for interaction with the database.

API Endpoints (Qualification Controller) with DTOs:
- [x] Create a new qualification:
```
POST /qualification
Headers:
- Content-Type: application/json
- Authorization: Bearer <token>
Body:
- reference (string): Unique reference of the qualification.
- title (string): Descriptive title of the qualification.
- description (string): Detailed description of the qualification.
- expires_at (datetime): Expiration date of the qualification.
Responses:
- 201 Accepted
- 400 Bad Request
```

- [x] Get list of qualifications:
```
GET /qualification
Headers:
- human-signature: <signature>
Responses:
- 200 OK with a list of active qualifications.
- 400 Bad Request
```

- [x] Delete qualification:
```
DELETE /qualification
Headers:
- Content-Type: application/json
- Authorization: Bearer <token>
Body:
- reference (string): Unique reference of the qualification.
Responses:
- 200 OK
- 400 Bad Request
```

- [x] Assign a qualification to a list of users:
```
POST /qualification/assign
Headers:
- Content-Type: application/json
- Authorization: Bearer <token>
Body:
- reference (string): Unique reference of the qualification.
- worker_addresses (string[]): Addresses of users to assign the qualification.
- worker_emails (string[]): Emails of users to assign the qualification.
Responses:
- 201 Accepted
- 400 Bad Request
```

- [x] Unassign a qualification from a list of users:
```
DELETE /qualification/unassign
Headers:
- Content-Type: application/json
- Authorization: Bearer <token>
Body:
- reference (string): Unique reference of the qualification.
- worker_addresses (string[]): Addresses of users to unassign the qualification.
- worker_emails (string[]): Emails of users to unassign the qualification.
Responses:
- 200 OK
- 400 Bad Request
```

- [x] Covered all methods with unit tests.

## How test the changes
`yarn test`

## Related issues
[Reputation Oracle] Qualification System
[#2190](https://github.com/humanprotocol/human-protocol/issues/2190)

2024-07-01 14:30 UTC, flopez7 commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts
> +      return {
```suggestion
      await this.qualificationRepository.createUnique(newQualification);
```

2024-07-01 14:37 UTC, flopez7 commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.repository.ts
> +    const queryBuilder = this.createQueryBuilder('qualifications').where(
Why don't you use typeorm clause?

```suggestion
    const queryBuilder = this.find({ where: { expiresAt: LessThan(currentDate) } });
```

2024-07-01 14:41 UTC, flopez7 commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts
> +    const result = await this.qualificationRepository.delete({ reference });
I would suggest creating a new method to delete in BaseRepository and catch the QueryFailedError there in case of failure

2024-07-01 14:44 UTC, flopez7 commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts
> +      users.push(...emailUsers);
Same here, create findByAddress and findByEmail in userRepository

2024-07-01 14:45 UTC, flopez7 commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts
> +    const qualification = await this.qualificationRepository.findOne({
Create findByReference in qualificationRepository

2024-07-04 14:20 UTC, portuu3 commented on packages/apps/reputation-oracle/server/src/common/config/env-schema.ts
> +  CRON_SECRET: Joi.string().required(),
```suggestion
```

2024-07-04 14:20 UTC, portuu3 commented on packages/apps/reputation-oracle/server/src/common/config/server-config.service.ts
> +  }
```suggestion
```

2024-07-04 14:21 UTC, portuu3 commented on packages/apps/reputation-oracle/server/src/common/constants/errors.ts
> +  FailedFetchQualifications = 'Failed to fetch qualifications',
Not referenced

2024-07-05 10:51 UTC, portuu3 requested changes

2024-07-05 10:51 UTC, portuu3 commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts
> +        const errorMessage = ErrorQualification.InvalidExpiresAt.replace(
The message says hours. But qualificationMinValidity seems to be seconds, am I right?

2024-07-05 10:51 UTC, portuu3 commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts
> +          expiresAt: qualificationEntity.expiresAt || null,
```suggestion
          expiresAt: qualificationEntity.expiresAt,
```

2024-07-05 14:23 UTC, portuu3 approved these changes

2024-07-05 14:23 UTC, merged