Feature/rep oracle/role based guard
humanprotocol/human-protocol pull request #2194
Opened 2024-06-26 09:18 UTC by eugenvoronov

## Description
Implemented a guard to handle role-based access control. This guard will ensure that only users with the appropriate roles can access certain routes and perform specific actions.

## Summary of changes
Created a roles guard
- Implement a guard that checks if the user has the necessary role to access a particular route.

Created a roles decorator
- Create a custom decorator to define the roles required for a route.

Applied roles guard and decorator to controllers

## How test the changes
`POST /qualification`

## Related issues
[Reputation Oracle] Qualification System
[#2190](https://github.com/humanprotocol/human-protocol/issues/2190)
[Reputation Oracle] Implement guard for role-based access control
[#2189](https://github.com/humanprotocol/human-protocol/issues/2189)

2024-06-26 11:37 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.controller.ts
> +  @Roles(Role.OPERATOR, Role.WORKER, Role.HUMAN_APP, Role.ADMIN)
I think it should use a signature auth guard instead of JWT.

2024-06-26 11:37 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.controller.ts
> +  @Roles(Role.OPERATOR, Role.WORKER, Role.HUMAN_APP, Role.ADMIN)
https://human-protocol.gitbook.io/hub/human-tech-docs/architecture/protocol-features/qualifications-system#get-list-of-qualifications

2024-06-26 11:38 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.controller.ts
> +  @Roles(Role.OPERATOR, Role.WORKER, Role.HUMAN_APP, Role.ADMIN)
cc @portuu3

2024-06-26 11:55 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/database/migrations/1719313669358-AddQualificationTable.ts
> +      `ALTER TABLE "hmt"."site_keys" DROP CONSTRAINT "FK_178ba06ffb4808dbb40e782231e"`,
This FK is already dropped here:
https://github.com/humanprotocol/human-protocol/blob/af4b1c187f9b3194e7b2c94878d0455746b6e531/packages/apps/reputation-oracle/server/src/database/migrations/1718970966064-RenameAndModifyUserRoleEnum.ts#L10

2024-06-26 11:57 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/database/migrations/1719313669358-AddQualificationTable.ts
> +      `DROP INDEX "hmt"."IDX_031d62ae4b47ae1a15c3d68179"`,
This index is already dropped here:
https://github.com/humanprotocol/human-protocol/blob/af4b1c187f9b3194e7b2c94878d0455746b6e531/packages/apps/reputation-oracle/server/src/database/migrations/1718970966064-RenameAndModifyUserRoleEnum.ts#L12

2024-06-26 12:06 UTC, Dzeranov requested changes
Please, cleanup migration file first.

2024-06-26 12:06 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/database/migrations/1719313669358-AddQualificationTable.ts
> +      `ALTER TABLE "hmt"."site_keys" ALTER COLUMN "created_at" DROP DEFAULT`,
Altered here:
https://github.com/humanprotocol/human-protocol/blob/af4b1c187f9b3194e7b2c94878d0455746b6e531/packages/apps/reputation-oracle/server/src/database/migrations/1718970966064-RenameAndModifyUserRoleEnum.ts#L16

2024-06-26 12:06 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/database/migrations/1719313669358-AddQualificationTable.ts
> +      `ALTER TABLE "hmt"."site_keys" ALTER COLUMN "updated_at" DROP DEFAULT`,
Altered here: 
https://github.com/humanprotocol/human-protocol/blob/af4b1c187f9b3194e7b2c94878d0455746b6e531/packages/apps/reputation-oracle/server/src/database/migrations/1718970966064-RenameAndModifyUserRoleEnum.ts#L19

2024-06-26 12:06 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/database/migrations/1719313669358-AddQualificationTable.ts
> +      `ALTER TABLE "hmt"."site_keys" ADD CONSTRAINT "FK_266dc68bd3412cb17b5d927b30c" FOREIGN KEY ("user_id") REFERENCES "hmt"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
Altered here:
https://github.com/humanprotocol/human-protocol/blob/af4b1c187f9b3194e7b2c94878d0455746b6e531/packages/apps/reputation-oracle/server/src/database/migrations/1718970966064-RenameAndModifyUserRoleEnum.ts#L38

2024-06-26 12:06 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/database/migrations/1719313669358-AddQualificationTable.ts
> +      `CREATE TYPE "hmt"."users_type_enum" AS ENUM('OPERATOR', 'EXCHANGE_ORACLE', 'RECORDING_ORACLE', 'WORKER')`,
https://github.com/humanprotocol/human-protocol/blob/af4b1c187f9b3194e7b2c94878d0455746b6e531/packages/apps/reputation-oracle/server/src/database/migrations/1718970966064-RenameAndModifyUserRoleEnum.ts#L28

2024-06-26 12:06 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/database/migrations/1719313669358-AddQualificationTable.ts
> +    await queryRunner.query(`DROP TYPE "hmt"."users_type_enum_old"`);
https://github.com/humanprotocol/human-protocol/blob/af4b1c187f9b3194e7b2c94878d0455746b6e531/packages/apps/reputation-oracle/server/src/database/migrations/1718970966064-RenameAndModifyUserRoleEnum.ts#L33

2024-06-26 12:06 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/database/migrations/1719313669358-AddQualificationTable.ts
> +      `CREATE UNIQUE INDEX "IDX_271231e19f913b8a0cf028e9e7" ON "hmt"."site_keys" ("site_key", "type") `,
https://github.com/humanprotocol/human-protocol/blob/af4b1c187f9b3194e7b2c94878d0455746b6e531/packages/apps/reputation-oracle/server/src/database/migrations/1718970966064-RenameAndModifyUserRoleEnum.ts#L35

2024-06-26 12:52 UTC, Dzeranov requested changes

2024-06-26 12:52 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.repository.ts
> +      'qualifications.expiresAt > :currentDate',
Won't return qualifications without an expiration data.

2024-06-26 12:52 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts
> +      if (providedExpiresAt <= new Date()) {
Maybe lets add some reasonable delta here?
For example, qualification should be valid for at least an hour or a day.

2024-06-26 12:52 UTC, Dzeranov commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts
> +      this.logger.log(`Failed to fetch credentials: ${error.message}`);
qualifications, not credentials

2024-06-27 06:15 UTC, eugenvoronov commented on packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts
> +      if (providedExpiresAt <= minimumValidUntil) {
Do you think we should update the error message and tell the user how much they should add to the expiration date?

2024-07-05 10:51 UTC, closed without merging