[Fortune] Lower case addresses in signatures
humanprotocol/human-protocol pull request #2213
Opened 2024-06-29 11:43 UTC by eugenvoronov

## Description
In the signature verification and sign message functions if the message contains a an address convert it to lower case.

## Summary of changes
Implemented `toLowerCase`.

## How test the changes
`yarn test`

## Related issues
[Fortune Exchange Oracle] Lower case addresses in signatures
[#2206](https://github.com/humanprotocol/human-protocol/issues/2206)
[Fortune Recording Oracle] Lower case addresses in signatures
[#2207](https://github.com/humanprotocol/human-protocol/issues/2207)

2024-07-11 08:53 UTC, portuu3 requested changes

2024-07-11 08:53 UTC, portuu3 commented on packages/apps/fortune/exchange-oracle/server/src/common/utils/index.ts
> +export function toLowerCase(input: string | undefined): string {
This doesn't make sense, just use native toLowerCase

2024-07-12 10:37 UTC, portuu3 requested changes

2024-07-12 10:37 UTC, portuu3 commented on packages/apps/fortune/exchange-oracle/server/src/common/guards/signature.auth.ts
> +    const { escrow_address, ...restBody } = request.body;
We should the lower case conversion in the signature verification (method verifySignature). If we do it here and we call verifySignature from somewhere else the issue will persist. So this changes here are not required

2024-07-12 10:37 UTC, portuu3 commented on packages/apps/fortune/recording-oracle/src/modules/job/job.service.spec.ts
> +        escrowAddress: MOCK_ADDRESS.toLowerCase(),
If the implementation is correct we should not requiered to pass lowercase in the tests, in should be done internally.

2024-07-12 11:04 UTC, Dzeranov commented
@eugenvoronov @portuu3 
Why can't we just modify a bit the structure here?
As far as I can see, we're actually verifying a specific data structure:
```
{
  chain_id: ChainId,
  escrow_address: string,
  event_type: EventType,
  event_data?: EventData
}
```
So we actually don't need to apply any `.stringify()` before data comes to `.verifySignature()`.
In this case we can specify an exact type of data/message and make all the necessary case conversions inside e.g.

```
export function verifySignature(
  data: WebhookDto,
  signature: string,
  addresses: string[],
): boolean {
  // set escrow_address to lower case
  // stringify a message
  const signer = recoverSigner(message, signature);

  ...
  }

  return true;
}
```

2024-07-15 15:05 UTC, portuu3 submitted a review, later dismissed

2024-07-15 15:14 UTC, portuu3 approved these changes

2024-07-15 15:14 UTC, merged