Add SKALE to supported chains
humanprotocol/human-protocol pull request #342
Opened 2023-03-20 16:14 UTC by payvint

Add SKALE graph node
Add SKALE to supported chains
Fix wallet connect problem after wage update

2023-03-21 08:17 UTC, portuu3 requested changes

2023-03-21 08:19 UTC, payvint commented on packages/core/.openzeppelin/unknown-1273227453.json
Yeap, good catch

2023-03-21 08:23 UTC, payvint commented on packages/apps/escrow-dashboard/src/constants/index.ts
Should work with the latest public link

2023-03-21 08:36 UTC, portuu3 requested changes
![image](https://user-images.githubusercontent.com/61605646/226554113-d3db0f02-c730-40cc-99e3-22961656d33e.png)

2023-03-23 07:33 UTC, portuu3 requested changes
check comments and solve conflicts

2023-03-23 07:33 UTC, portuu3 commented on packages/sdk/typescript/subgraph/src/mapping/Escrow.ts
> +export function handleCancelled(event: Cancelled): void {
is there a reason to add the event in this function?

2023-03-23 07:33 UTC, portuu3 commented on packages/sdk/typescript/subgraph/src/mapping/Escrow.ts
> +export function handleCompleted(event: Completed): void {
is there a reason to add the event in this function?

2023-03-23 10:11 UTC, payvint commented
> ![image](https://user-images.githubusercontent.com/61605646/226554113-d3db0f02-c730-40cc-99e3-22961656d33e.png)

This problem should be fixed after changing a token and updating subgraph

2023-03-23 10:50 UTC, portuu3 submitted a review, later dismissed

2023-03-23 10:56 UTC, portuu3 submitted a review, later dismissed

2023-03-23 11:10 UTC, merged