Resolve Certik v3 Reports
humanprotocol/human-protocol pull request #437
Opened 2023-05-02 17:15 UTC by leric7

## Description

Certik v3 report is asking to write more comprehensive documentation about `bulkPayout` function for clarity.

## Summary of changes

- Fix unnecessary usage of `SafeMath` utils in `HMToken.sol`.
- Add meaningful comments to `bulkPayout` function of `Escrow.sol`.

## How test the changes

## Related issues
[Keywords for linking issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

## Operational checklist

- [ ] All new functionality is covered by tests
- [ ] Any related documentation has been changed or added

2023-05-04 22:18 UTC, mrhouzlane requested changes

2023-05-04 22:18 UTC, mrhouzlane commented on packages/core/contracts/Escrow.sol
> +     * Escrow needs to be complted / cancelled, so that it can be paid out.
Add **@dev tag** from L186 to L193 because if you run `solc --devdoc --pretty-json Escrow.sol`  you won't have the expected file.

2023-05-05 00:58 UTC, mrhouzlane commented on packages/core/contracts/Escrow.sol
> +     * @notice Bulk payout workers
performs Bulk payout to multiple workers

2023-05-05 00:59 UTC, mrhouzlane commented on packages/core/contracts/Escrow.sol
> +     * @param _amounts Array of amounts
Array of amounts to be paid to each recipient.

2023-05-05 01:00 UTC, mrhouzlane commented on packages/core/contracts/Escrow.sol
> +     * @param _url URL of the results
URL storing results as transaction details

2023-05-05 01:04 UTC, mrhouzlane commented on packages/core/contracts/Escrow.sol
>       */
Optional(add) : This contract is only callable it the contract is not broke, not launched, not paid, not expired, by trusted parties.

2023-05-05 01:04 UTC, mrhouzlane requested changes
Modifiers comments (optional)

2023-05-05 01:05 UTC, mrhouzlane commented
Besides @dev tag this looks good to me.

2023-05-05 10:30 UTC, portuu3 requested changes

2023-05-05 10:30 UTC, portuu3 commented on packages/core/contracts/Escrow.sol
> +            if (finalAmounts[i] > 0) {
we might need to add require with this, the only for this to be 0 is that amount passed is 0 and this shouldn't happen

2023-05-05 12:45 UTC, mrhouzlane requested changes

2023-05-05 12:45 UTC, mrhouzlane commented on packages/core/contracts/Escrow.sol
>          ) = finalizePayouts(_amounts);
FinalizePayouts should have checks for amounts array : 

```require(_amounts.length > 0, "Amounts should not be empty");
for (uint256 j; j < _amounts.length; j++) {
    require(_amounts[j] > 0, "Amount should be greater than zero");
    // rest of the loop code
}
```

2023-05-05 13:36 UTC, portuu3 commented on packages/core/contracts/Escrow.sol
> +            if (finalAmounts[i] > 0) {
ok, lets keep it as it is and I will ask Alex if we should add a limit of fees

2023-05-05 13:44 UTC, portuu3 submitted a review, later dismissed

2023-05-05 15:19 UTC, portuu3 approved these changes

2023-05-05 15:50 UTC, merged

2023-05-08 08:10 UTC, mrhouzlane commented on packages/core/contracts/Escrow.sol
> +     * @dev Performs bulk payout to multiple workers
This should stay @notice : Explain to an end user what this doe
@dev is the tag to :  Explain to a developer any extra details
@notice : Performs bulk payout to multiple workers 
@dev Escrow needs to be completed ... 

I think certik wanted to have a clear comments : 

- solc --devdoc --pretty-json Escrow.sol will return details with comments.

to check [https://coinsbench.com/natspec-the-right-way-to-comment-ethereum-smart-contracts-6762082252d4]