Python Escrow SDK
humanprotocol/human-protocol pull request #458
Opened 2023-05-10 15:00 UTC by flopez7

## Description

Develop the Escrow SDK

## Summary of changes

- Create EscrowClient class
- Create create_escrow method
- Create setup method
- Create create_and_setup_escrow method
- Create fund method
- Create store_results method
- Create complete method
- Create bulk_payout method
- Create cancel method
- Create abort method
- Create add_trusted_handlers method
- Create get_balance method
- Create get_manifest_url method
- Create get_results_url method
- Create get_token_address method
- Create get_status method

## How test the changes

Run make run-test inside python SDK folder

## Related issues
#443 

## Operational checklist

- [x] All new functionality is covered by tests
- [ ] Any related documentation has been changed or added

2023-05-11 10:09 UTC, Dzeranov requested changes

2023-05-11 10:09 UTC, Dzeranov commented on packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
> +            raise EscrowClientError("Escrow does not have enough balance")
Let's change it to `f"Escrow does not have enough balance. Current balance: {balance}. Amounts: {sum(amounts)}"`

2023-05-11 10:09 UTC, Dzeranov commented on packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
> +            raise EscrowClientError("Invalid hash")
See above about a bit more informative error messages.

2023-05-11 10:09 UTC, Dzeranov commented on packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
> +            raise EscrowClientError("Invalid address")
See above about a bit more informative error messages.

2023-05-11 10:09 UTC, Dzeranov commented on packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
> +            raise EscrowClientError("Invalid address")
See above about a bit more informative error messages.

2023-05-11 10:09 UTC, Dzeranov commented on packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
> +            str: The address of the escrow created
We don't anything in this method.

2023-05-11 10:09 UTC, Dzeranov commented on packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
> +            raise EscrowClientError("Invalid address")
See above about a bit more informative error messages.

2023-05-12 15:00 UTC, Dzeranov approved these changes

2023-05-15 10:01 UTC, portuu3 requested changes

2023-05-15 12:57 UTC, leric7 commented on packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
> +        if 0 > amount:
```suggestion
        if 0 >= amount:
```

2023-05-16 11:14 UTC, Dzeranov approved these changes
lgtm

2023-05-16 14:06 UTC, portuu3 approved these changes

2023-05-16 14:06 UTC, portuu3 approved these changes

2023-05-16 14:11 UTC, merged