Feat/exchange oracle
humanprotocol/human-protocol pull request #575
Opened 2023-06-19 14:49 UTC by flopez7

## Description

Create a first backend version for exchange oracle

## Summary of changes

Add a new Nestjs project with:

- GET /job/details/:chainId/:escrowAddress
- GET /job/pending/:chainId/:workerAddress
- POST /job/solve

## How test the changes

`cd packages/apps/fortune/exchange-oracle/server && yarn test`

## Related issues
Close #483 

## Operational checklist

- [x] All new functionality is covered by tests
- [x] Any related documentation has been changed or added

2023-06-20 15:49 UTC, portuu3 requested changes

2023-06-20 15:49 UTC, portuu3 commented on packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
> +      (escrow) => !this.storage[escrow]?.includes(workerAddress),
```suggestion
      (escrow: string) => !this.storage[escrow]?.includes(workerAddress),
```

2023-06-20 15:49 UTC, portuu3 commented on packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
> +      (recordingOracleURL || 'http://localhost:3005') + '/job/solve',
if recordingOracleURL is null it should throw an error

2023-06-21 07:32 UTC, flopez7 commented on packages/examples/fortune-v2/recording-oracle/src/main.ts
Because we have been using that port for recording for a long time and to avoid conflicts with all apps using the same port

2023-06-21 09:12 UTC, portuu3 approved these changes

2023-06-21 10:13 UTC, portuu3 approved these changes

2023-06-21 10:23 UTC, merged