[Fortune] [Exchange oracle] Get manifest data from reputation oracle
humanprotocol/human-protocol pull request #691
Opened 2023-07-17 12:36 UTC by leric7

## Description

Exchange Oracle should get the manifest from Reputation Oracle instead of pulling it from s3 bucket directly.

## Summary of changes
- Added a http request to reputation endpoint to get manifest.
- Updated test cases.

## How test the changes

## Related issues
[Keywords for linking issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

Closes #656 

## Operational checklist

- [x] All new functionality is covered by tests
- [x] Any related documentation has been changed or added

2023-07-17 13:06 UTC, flopez7 submitted a review, later dismissed

2023-07-17 13:17 UTC, portuu3 requested changes

2023-07-17 13:17 UTC, portuu3 commented on packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
> +      KVStoreKeys.webhook_url,
not webhook_url, just url

2023-07-18 12:56 UTC, portuu3 approved these changes

2023-07-18 12:57 UTC, merged