[Subgraph] New schema implementation
humanprotocol/human-protocol pull request #728
Opened 2023-07-26 17:04 UTC by leric7

## Description

Subgraph schemas are re-defined based on new design of Job Launcher, and Escrow Dashboard.
https://app.diagrams.net/#G1WCSJhsWy4irN0wgxlPbePcT0uN5pbtTx

## Summary of changes

- Updated subgraph schema definition
- Updated subgraph handlers to properly save data
- Updated test cases

## How test the changes

## Related issues
[Keywords for linking issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

Closes #721 

## Operational checklist

- [x] All new functionality is covered by tests
- [x] Any related documentation has been changed or added

2023-07-27 14:29 UTC, portuu3 requested changes
can we create a new subgraph and deploy it? I would suggest to use mumbai

2023-08-16 12:29 UTC, portuu3 requested changes

2023-08-16 16:39 UTC, leric7 commented on packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
> +        launcher_address: Optional[str] = None,
Will revisit this on #758

2023-08-16 16:39 UTC, leric7 commented on packages/sdk/typescript/human-protocol-sdk/src/graphql/queries/escrow.ts
> +    $launcherAddress: String
Will revisit this on #758

2023-08-16 16:39 UTC, leric7 commented on packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
> +        escrowClient.getEscrowsFiltered({ launcherAddress: requesterAddress })
Will revisit this on #758

2023-08-16 16:39 UTC, leric7 commented on packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
> +        launcherAddress: requesterAddress,
Will revisit this on #758

2023-08-16 16:39 UTC, leric7 commented on packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts
> +  launcherAddress?: string;
Will revisit this on #758

2023-08-18 14:56 UTC, portuu3 approved these changes

2023-08-18 15:07 UTC, merged