[Job Launcher] Added testnet and mainnet setup
humanprotocol/human-protocol pull request #763
Opened 2023-08-10 13:54 UTC by eugenvoronov

## Description
Added an env variable to choose if the job launcher should use testnets or mainnet.

## Summary of changes
- Added `WEB3_ENV` to `.env`
- Updated web3 service `getSigner` method
- Updated unit tests

## How test the changes
`yarn test`

## Related issues
[Job Launcher - Testnet and mainnet setup#750](https://github.com/humanprotocol/human-protocol/issues/750)

2023-08-10 15:08 UTC, portuu3 requested changes
Add a check of chain id in job service when the jobs are requested

2023-08-10 15:08 UTC, portuu3 commented on packages/apps/job-launcher/server/src/modules/web3/web3.module.ts
> +  providers: [Web3Service, Logger],
why is logger a provider here?

2023-08-11 04:35 UTC, eugenvoronov commented on packages/apps/job-launcher/server/src/modules/web3/web3.module.ts
> +  providers: [Web3Service, Logger],
Yes, it's redundant

2023-08-11 06:25 UTC, portuu3 requested changes

2023-08-11 06:25 UTC, portuu3 commented on packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
add a test passing wrong chainId and making sure that the chainId validation is being called

2023-08-11 09:47 UTC, portuu3 requested changes

2023-08-11 09:47 UTC, portuu3 commented on packages/apps/job-launcher/server/src/common/enums/web3.ts
> +export enum UserStatus {
I think this should not be here

2023-08-11 09:47 UTC, portuu3 commented on packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
the same for cvat

2023-08-11 09:56 UTC, eugenvoronov commented on packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
copy paste, will remove

2023-08-11 09:57 UTC, eugenvoronov commented on packages/apps/job-launcher/server/src/common/enums/web3.ts
> +export enum UserStatus {
copy paste, will remove

2023-08-15 09:59 UTC, portuu3 requested changes

2023-08-15 11:54 UTC, portuu3 approved these changes

2023-08-15 12:42 UTC, merged