feat: [Core] Add exchange oracle to escrow contract
humanprotocol/human-protocol pull request #861
Opened 2023-09-01 15:09 UTC by leric7

## Description

We need to keep track of exchange oracle from escrow contract.

## Summary of changes
- Core
  - Two new local variables `exchangeOracle`, and `exchangeOracleFee` is added to `Escrow` contract.
  - `setup` function is updated accordingly.
  - `bulkPayout` function is updated to handle fee payout to exchange oracle.
- Subgraph
  - `Escrow` entity is updated to have two more fields.
  - `Pending` event handler is updated to track data properly.
- SDK
  - `setup` function is updated.
  - Added `getExchangeOracleAddress()` function.

## How test the changes

## Related issues
[Keywords for linking issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

Closes #852

## Operational checklist

- [x] All new functionality is covered by tests
- [ ] Any related documentation has been changed or added

2023-09-02 00:04 UTC, portuu3 approved these changes

2023-09-02 00:11 UTC, portuu3 requested changes
Fix reference to sdk in `packages/apps/job-launcher/server/src/modules/job/job.service.ts`.
Also have in mind we have to wait to merge this to develop otherwise we will break Job Launcher that is being used by Tony, since the contracts are not deployed yet.

2023-09-11 13:22 UTC, flopez7 submitted a review, later dismissed

2023-09-18 12:48 UTC, portuu3 approved these changes

2023-09-18 14:32 UTC, merged

2023-09-20 12:40 UTC, eugenvoronov commented on packages/core/contracts/Escrow.sol
> +            _safeTransfer(exchangeOracle, exchangeOracleFee);
Here

2023-09-20 12:47 UTC, eugenvoronov commented on packages/core/contracts/Escrow.sol
> +        exchangeOracleFeePercentage = _exchangeOracleFeePercentage;
->