[SDK] Implemented getEscrow and getDetails method updated
humanprotocol/human-protocol pull request #908
Opened 2023-09-19 08:33 UTC by eugenvoronov

## Description
Implemented the ability to retrieve a single escrow's data by escrow address. Now associated escrow data can be fetched without relying on other filters.

## Summary of changes
**Added getEscrow function in escrowClient.**
- This function allows fetching an escrow by escrow address.
- It uses the GET_ESCROW_BY_ADDRESS_QUERY GraphQL query to get the data.
- An error is thrown if an invalid ethereum address is provided.
- Returns null if the escrow isn't found.

**Added unit tests for getEscrowByAddress.**
- Tests cover scenarios where an invalid address is provided, a valid address with no corresponding escrow, and a valid address with a corresponding escrow.

**Modified GraphQL queries to include GET_ESCROW_BY_ADDRESS_QUERY.**

**Updated getDetails method in Job Launcher Server**
 

## How test the changes
`yarn test`

## Related issues
[[Job Launcher] [SDK] Implement getEscrow method to SDK and use it in getDetails method#892](https://github.com/humanprotocol/human-protocol/issues/892)

2023-09-20 08:04 UTC, flopez7 approved these changes

2023-09-20 14:42 UTC, flopez7 commented on packages/apps/job-launcher/server/src/modules/job/job.dto.ts
> +  exchangeOracleAddress?: string;
The var is nullable, but the validator forces to have a value

2023-09-20 14:42 UTC, flopez7 commented on packages/apps/job-launcher/server/src/modules/job/job.dto.ts
> +  recordingOracleAddress?: string;
Same here

2023-09-20 14:42 UTC, flopez7 commented on packages/apps/job-launcher/server/src/modules/job/job.dto.ts
> +  reputationOracleAddress?: string;
And here

2023-09-20 22:56 UTC, leric7 requested changes
We are moving `getEscrows` function to `EscrowUtils` of the SDK. I think it'll be better define this new function in that module as well. We'll need `chainId` as function argument.

2023-09-21 02:43 UTC, portuu3 commented
@eugenvoronov please create a task for getEscrow function on python SDK and also sdk docs have to be updated

2023-09-21 07:29 UTC, eugenvoronov commented
[@flopez7 ](https://github.com/humanprotocol/human-protocol/issues/915)

2023-09-22 11:52 UTC, flopez7 requested changes

2023-09-25 07:47 UTC, flopez7 submitted a review, later dismissed

2023-09-26 12:51 UTC, leric7 submitted a review, later dismissed

2023-09-26 12:53 UTC, merged