[SDK][Typescript][Python] Add network array to getEscrows filter
humanprotocol/human-protocol pull request #913
Opened 2023-09-20 14:15 UTC by flopez7

## Description

Add network array to getEscrows filter to retrieve information from all networks

## How test the changes

`yarn test` for Typescript and `make run-test` for Python

## Operational checklist

- [x] All new functionality is covered by tests
- [ ] Any related documentation has been changed or added

2023-09-20 22:48 UTC, leric7 commented
We need to update SDK doc on gitbook as well.

2023-09-20 22:51 UTC, leric7 requested changes
We have /examples directory for both Python/Typescript SDK. Let's update example, as well. This way, you can make sure your updates are working end-to-end. In addition, we need to update SDK docs on GitBook.

2023-09-21 09:57 UTC, flopez7 commented
> We have /examples directory for both Python/Typescript SDK. Let's update example, as well. This way, you can make sure your updates are working end-to-end. In addition, we need to update SDK docs on GitBook.

@leric7 I have it in mind, I was waiting for the approval to update the documentation only once.

2023-09-22 07:14 UTC, portuu3 approved these changes

2023-09-22 07:58 UTC, merged