add codeql analysis
humanprotocol/human-protocol pull request #914
Opened 2023-09-20 22:20 UTC by leric7

## Description

## Summary of changes

## How test the changes

## Related issues
[Keywords for linking issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

## Operational checklist

- [ ] All new functionality is covered by tests
- [ ] Any related documentation has been changed or added

2023-09-21 01:12 UTC, portuu3 requested changes

2023-09-21 01:12 UTC, portuu3 commented on packages/apps/job-launcher/server/src/app.module.ts
We cannot remove this because is necessary to make swagger work on vercel

2023-09-21 01:12 UTC, portuu3 commented on packages/apps/job-launcher/server/src/main.ts
We cannot remove this because is necessary to make swagger work on vercel

2023-09-21 01:12 UTC, portuu3 commented on packages/apps/job-launcher/server/swagger-static/swagger-ui-bundle.js
We cannot remove this because is necessary to make swagger work on vercel

2023-09-21 01:12 UTC, portuu3 commented on packages/apps/job-launcher/server/swagger-static/swagger-ui-standalone-preset.js
We cannot remove this because is necessary to make swagger work on vercel

2023-09-21 01:12 UTC, portuu3 commented on packages/apps/job-launcher/server/swagger-static/swagger-ui.css
We cannot remove this because is necessary to make swagger work on vercel

2023-09-21 13:40 UTC, leric7 commented
@portuu3 , I enabled the preview deployment, and swagger seems to be working fine.
https://job-launcher-server-git-feat-codeql-humanprotocol.vercel.app/swagger

2023-09-22 01:33 UTC, portuu3 commented
> @portuu3 , I enabled the preview deployment, and swagger seems to be working fine. https://job-launcher-server-git-feat-codeql-humanprotocol.vercel.app/swagger

I don't know how you did to deploy it, but I deployed the last commit on feat/codeql and still does not work:
<img width="1373" alt="image" src="https://github.com/humanprotocol/human-protocol/assets/61605646/769e7f8c-174d-4e50-9907-107d9fc89313">

<img width="1505" alt="image" src="https://github.com/humanprotocol/human-protocol/assets/61605646/0ee49d99-3a4e-475e-a7a9-d74d4ef6651a">

2023-09-27 08:41 UTC, portuu3 approved these changes

2023-09-27 15:07 UTC, merged