Reconfiguration of recording oracle to Deno based
humanprotocol/human-protocol pull request #98
Opened 2023-01-02 18:30 UTC by UncleTom29

2023-01-03 12:59 UTC, posix4e requested changes

2023-01-03 12:59 UTC, posix4e commented on packages/examples/fortune/recording-oracle/src/contracts/EscrowAbi.json
> +[
Please do not checkin json of abi

2023-01-09 09:21 UTC, foufrix commented
Hi, after trying out your repo, I can setup the escrow, but when I send the first message I get an axios error :
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/16646581/211275413-d4d77bb8-61d4-415a-acf5-003a7c7775ed.png">

The two first with uncaught promise come from my extension, so you can neglect them

Those are the one important : 
<img width="543" alt="image" src="https://user-images.githubusercontent.com/16646581/211275638-413fdce6-2ece-4dbe-a983-4c56111ef8a6.png">

2023-01-09 22:02 UTC, posix4e requested changes
Stop checking in Escrow.json. That is not ok

2023-01-09 22:04 UTC, posix4e commented on packages/examples/fortune/recording-oracle/hardhat.config.js
> +/** @type import('hardhat/config').HardhatUserConfig */
why are you reformatting this file?

2023-01-09 22:04 UTC, posix4e commented on packages/examples/fortune/recording-oracle/LICENSE
> +                    GNU GENERAL PUBLIC LICENSE
Why are you checking in GPL? That's not ok

2023-01-09 22:07 UTC, UncleTom29 commented
Sorry for that, it was used to test. I’ll remove it now
Moreover during deployment, there’s no way to mirror the NPM workspace init
in Deno. So there’s no way to import the ***@***.***/core” module. It
might cause the Deno app not to run properly.

On Mon, Jan 9, 2023 at 11:02 PM Alex Newman ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Stop checking in Escrow.json. That is not ok
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/humanprotocol/human-protocol/pull/98#pullrequestreview-1241266274>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWQ3PDZSMYL6GJH6ONEQITTWRSDJFANCNFSM6AAAAAATPASVSI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-09 22:26 UTC, UncleTom29 commented
@posix4e requested changes implemented

2023-02-03 13:31 UTC, closed without merging